package br.com.iuriraredu.ecommerce.mapper;

import br.com.iuriraredu.ecommerce.dto.ProductRequestDTO;
import br.com.iuriraredu.ecommerce.dto.ProductResponseDTO;
import br.com.iuriraredu.ecommerce.entity.Product;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring")
public interface ProductMapper {

    // id is never trusted from the request body — always generated by the database.
    // active defaults to true when the client doesn't send it, matching the previous manual logic.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "active", source = "active", defaultValue = "true")
    Product toEntity(ProductRequestDTO dto);

    // Updates an existing managed entity in place instead of creating a new one — same id,
    // same JPA identity, only the fields present in the DTO change.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "active", source = "active", defaultValue = "true")
    void updateEntityFromDto(ProductRequestDTO dto, @MappingTarget Product product);

    ProductResponseDTO toResponseDTO(Product product);
}
