spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Opção 1: Em memória (recomendo para desenvolvimento)
#spring.datasource.url=jdbc:h2:mem:ecommerce;DB_CLOSE_DELAY=-1

# Opção 2: Em arquivo com parâmetros de fechamento (se precisar persistir)
spring.datasource.url=jdbc:h2:file:./data/ecommerce;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE

spring.datasource.driver-class-name=org.h2.Driver # Talvez seja mais interessante utilizar um application-local.yml para o H2 e o application.yml para um banco de dados como Postgres, MariaDB etc.
spring.datasource.username=sa # Qual o motivo disso não estar em uma env também? Outros campos também deveriam estar em envs.
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop # Só se utiliza isso para testes, em produção provavelmente vai ser none ou validate enquanto a criação das tabelas é feito por um versionador como flyway ou liquibase.
spring.jpa.show-sql=true # Desliga essa parada em produção, para testes locais está OK. Para testes locais também é interessante habilitar as estatísticas para ver se não tem query N+1, mas habilite apenas para desenvolvimento local.
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:dev-only-secret}